<?php

function clock_angle_menu() {
    $items = array();
    $items['clock_angle'] = array(
        'title' => 'Clock Angle',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('clock_angle_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['clock_angle_success'] = array(
        'title' => 'Success',
        'page callback' => 'clock_angle_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function clock_angle_form() {
    $form['minute'] = array(
        '#title' => 'Minute',
        '#type' => 'textfield',
        '#description' => t('Enter the minute amount'),
    );

    $form['hour'] = array(
        '#title' => 'Hour',
        '#type' => 'textfield',
        '#description' => t('Enter the hour'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'GO!',
    );
    return $form;
}

function clock_angle_form_submit($form, &$form_state) {
    $minute = $form_state['values']['minute'];
    $hour = $form_state['values']['hour'];

    $minute = $minute % 60;
    $hour = $hour % 12;

    $minute_degree = $minute * 6;
    $hour_degree = $hour * 30;
    $difference = $hour_degree - $minute_degree;
    $clock_angle = abs($difference);

    $_SESSION['clock_angle_output'] = $clock_angle;
    $form_state['redirect'] = 'clock_angle_success';
}

function clock_angle_success() {
    $output = '<p>The clock angle is ' . $_SESSION['clock_angle_output'] . ' degrees</p>';
    return $output;
}
